#!/bin/bash
set -x

# The directory in which to create the home directories
location='/home'

# Create a group for all students
groupadd inmates
# (Yes, hostel residents are called 'inmates'
#  as per the rulebooks. Rather fitting.)

# Create HAD's account
useradd --create-home -d "$location/HAD" "HAD"
sudo -u HAD touch "$location/HAD/mess.txt"

# Read lines from studentDetails.txt or stdin, and
# perform the required tasks
IFS="\n" readarray lines < "${1:-/dev/stdin}"
for line in "${lines[@]:1}"; do

    IFS=' ' read -r -a words <<<"$line"

    name=${words[0]}
    hostel=${words[2]}
    roomno=${words[3]}
    rollno=${words[1]}
    mess=${words[4]}
    messpref=${words[5]}

    # Create hostel directory if not exists
    hosteldir=$location/$hostel
    wardenname=warden_$hostel
    if ! [[ -d "$hosteldir" ]]; then
        mkdir "$hosteldir"
        # Add user for Warden
        useradd --create-home -d "$hosteldir/$hostel" "$wardenname"
        # Make the hostel directory belong to the Warden
        chown "$wardenname" "$hosteldir" && chgrp "$wardenname" "$hosteldir"
        # Add announcements.txt, feeDefaulters.txt
        echo $(ls -l "$hosteldir")
        sudo -u "$wardenname" touch "$hosteldir/announcements.txt"
        sudo -u "$wardenname" touch "$hosteldir/feeDefaulters.txt"
    fi

    # Create room directory if not exists
    homebase=$hosteldir/$(printf '%.3d' $roomno)

    if ! [[ -d "$homebase" ]]; then
        sudo -u "$wardenname" mkdir "$homebase"
    fi

    # Create user
    homedir=$homebase/$name
    useradd --create-home -d "$homedir" "$name"
    # ...and add them to the 'inmates'
    # group. This will come in handy later.
    usermod -a -G inmates "$name"

    # Create fees.txt so other commands can
    # find it
    sudo -u "$name" touch "$homedir/fees.txt"

    # Create userDetails.txt
    # Assumptions:
    # - all students are first-years
    # - all students are from ECE (obv. since best department :P )
    # - 'Month' refers to the month of
    #   account creation

    # writes details to file
    wd() {
        echo "$@" >> "$homedir/userDetails.txt"
    }

    sudo -u "$name" touch "$homedir/userDetails.txt"
    wd Name: "$name"
    wd Roll no.: "$rollno"
    wd Department: ECE
    wd Year: 1
    wd Hostel: "$hostel"
    wd Mess: "$mess"
    wd Month: "$(date +%m)"
    wd Mess Pref: "$messpref"

done
