#!/bin/bash

# The directory in which the home directories are 
# assumed to be
location='/home'



if [[ $(id -u) -ne 0 ]]; then
    echo "Please run as root"
    exit 0
fi

# Base permissions for existing directories - execute bit
# is needed to search/list directories.
# Write bit is needed to be able to create subdirectories.
IFS=$'\n' chmod 711 $(find "$location" -type d)

# No write access for all the 'fees' directories (see README)
# IFS=$'\n' chmod 511 $(find "$location" -name 'fees' -type d)

# Base permissions for existing files - only users can read
# their own files, and nothing else.
IFS=$'\n' chmod 400 $(find "$location" -type f)

# HAD can view/edit all files
setfacl -m user:HAD:rwx -R "$location"

# fee-breakup must be SUID HAD (see README)
chown HAD:HAD /usr/local/bin/fee-breakup
chmod 4755 /usr/local/bin/fee-breakup

# All students can edit mess.txt
setfacl -m group:inmates:rwx "$location"/HAD/mess.txt

mainfolders=($location/*)
hostels=(${mainfolders[@]/"${location}/HAD"/})
for hostel in "${hostels[@]}"; do

    wardendir=$hostel/${hostel##*/} # this is how we had chosen to name
                                    # the Wardens' home directories
    wardenname=$(stat --format '%U' "$wardendir")

    # Wardens can access any file in their own hostel
    # directory
    setfacl -m user:"$wardenname":rwx -R "$hostel"

done

