#!/bin/bash

# The directory in which the home directories are 
# assumed to be
location='/home'



if [[ $(id -u) -ne 0 ]]; then
    echo "Please run as root"
    exit 0
fi

# Ensure only users can access their own files
# (The group bit doesn't matter as all files'
# groups are those of their owners)
chmod 771 -R "$location"

# HAD can view/edit all files
setfacl -m user:HAD:rwx -R "$location"

# All students can edit mess.txt
setfacl -m group:inmates:rwx "$location"/HAD/mess.txt

mainfolders=($location/*)
hostels=(${mainfolders[@]/"${location}/HAD"/})
for hostel in "${hostels[@]}"; do

    wardendir=$hostel/${hostel##*/} # this is how we had chosen to name
                                    # the Wardens' home directories
    wardenname=$(stat --format '%U' "$wardendir")

    # Wardens can access any file in their own hostel
    # directory
    setfacl -m user:"$wardenname":rwx -R "$hostel"

done

